### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by alexander-adamenko** [alexander-adamenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by LegatikUA** [comment]
I observed something fairly early on at Apple, which I didn't know how to explain then, but have thought a about it since. While in most areas, the ratio between the excellent and the average is 2:1, in the software the ratio of good developer and the average programmer is rather 50:1 or even 100:1.
So I built much of my success in finding these very talented people. And they enjoy working together because they have never had the chance to do that before.

**Comment by alexander-adamenko** [comment]
Good job!
